name: Deploy Frontend Tubes

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Menginstall Depedencies 📦
        run: |
          cd src/frontend
          npm ci
      - name: Build Frontend 🔨
        run: |
          cd src/frontend
          npm run build
      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/frontend/build
